/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],  // Сканирует src для классов
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [  // Добавляем классы, чтобы они не удалялись
    'bg-black',
    'text-white',
    'bg-gray-900',
    'border-gray-600',
    'text-orange-400',
    'text-gray-300',
    'text-gray-400',
    'bg-orange-500',
    'hover:bg-orange-600',
    'bg-gray-800',
    'border-gray-600',
    'placeholder-gray-400',
    'grid',
    'grid-cols-1',
    'md:grid-cols-3',
    'gap-6',
    'py-12',
    'text-center',
    'max-w-md',
    'mx-auto',
    'space-y-4',
    'font-semibold',
    'mb-2',
    'mb-6',
    'mb-8',
    'text-xl',
    'text-2xl',
    'text-4xl',
    'font-bold',
    'p-3',
    'p-4',
    'p-6',
    'rounded',
    'rounded-lg',
    'shadow-lg',
    'w-full',
    'flex',
    'justify-between',
    'items-center',
    'ml-8',
    'space-x-4',
    'text-gray-300',
    'hover:text-orange-400',
    'flex-1',
    'max-w-4xl',
    'px-4',
    'py-8',
    'py-16',
    'mt-auto',
    'min-h-screen',
    'flex-col',
    'border-b',
    'border-t',
    'col-span-full'
  ]
}